package com.videoswipe.model.vo 
{
	/**
	 * ...
	 * @author  Ben Silburn
	 * 
	 * VideoMessageVO
	 * a generic class for holding all data for a video message
	 */
	public class VideoMessageVO
	{
		public var sessionID:String;	// generated by server, key to this session
		public var uid:String;			// uid of recording user
		public var streamname:String;	// name of recorded stream (without mp4/flv extension)

		public function VideoMessageVO( _o:Object = null) 
		{
			if (_o) {
				fillFromObject(_o);
			}
			
		}
		
		private function fillFromObject(_o:Object):void
		{
			for (var i:String in _o) {
				try {
					this[i] = _o[i];
				} catch (e:Error) {
					trace("VideoMessageVO:: fillFromObject: ERROR" );
				}
			}
		}
	}

}